### ISSUE TITLE
Could we get this uploaded to Supermarket?

### ISSUE THREAD

**Issue by jblaine** [bflad/chef-lastrun_handler#1]
Could we get this uploaded to Supermarket?

**Comment by jmaziarz** [comment]
+1

**Comment by bflad** [comment]
I'll get this pushed up tomorrow

**Comment by bflad** [comment]
All set! 0.1.0 uploaded to Supermarket: https://supermarket.chef.io/cookbooks/lastrun_handler

**Comment by jblaine** [comment]
Thanks!
